version: '3'
services:
    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
        - "8080:80"  # Expose port 8080 on the host to port 80 on the container
        volumes:
        - ./:/var/www
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: Dockerfile
            container_name: laravel_app
            volumes:
                - ./:/var/www
            networks:
                - laravel_network
            depends_on:
                - mysql
    mysql:
        image: 'mysql:8.0'
        container_name: laravel_db
        environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laravel
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network
    queue:
        build:
        context: .
        dockerfile: Dockerfile
        container_name: laravel_queue
        command: php artisan queue:work
        depends_on:
            - db
            - app
        networks:
        - laravel_network

networks:
    laravel_network:
        driver: bridge
volumes:
    db_data:
